### ISSUE TITLE
Looker Query ID API Patch

### ISSUE THREAD

**Issue by jtorreio** [looker-open-source/looker_deployer#148]
Looker recently patched the platform to [Disallow Numeric Query Ids](https://cloud.google.com/looker/docs/best-practices/query-id-update-instructions). Since this was rolled out errors show when running ldeploy content export. Temporarily toggling off this enabled ldeploy to function as expected. 

![image (6)](https://github.com/looker-open-source/looker_deployer/assets/45767226/5676494a-7c62-4ba9-95de-834d29b644b6)

@drstrangelooker

**Comment by drstrangelooker** [comment]
Can you update gazer to the latest version (v0.3.13) with `gem update gazer` then test? That should resolve this issue.

**Comment by drstrangelooker** [comment]
@AdamMinton if the Gazer update isn't enough we will need you to look at this.

**Comment by jacobakh** [comment]
Hi @drstrangelooker @AdamMinton ,

I'm getting the same issue as @jtorreio. 

However, it is happening when I run `ldeploy content import`. I get a generic looker_sdk error. As suggested, I tried `gem update gazer ` and this did not resolve the issue.

Here is a screenshot of the error:

<img width="859" alt="image" src="https://github.com/looker-open-source/looker_deployer/assets/20731762/ddc8acc8-62ea-4ac5-a44d-c3658b7f8aff">

I've updated looker_deployer and looker_sdk and it hasn't done the trick either.

This is a high priority issue as we are blocked from deploying any Looker content to our instances. Can you please investigate? 

Please let me know if you need anything from me. Thank you!

**Comment by drstrangelooker** [comment]
I don't have any idea here. This is coming from the Python SDK for looker, so the `gem update gazer`  wouldn't have any impact. @AdamMinton do you have any ideas?

**Comment by drstrangelooker** [comment]
Closing the original issue after opening new issue to track the one raised by @jacobakh

**Comment by jacobakh** [comment]
Hi @drstrangelooker ,

Is it possible your package is making the call to looker-sdk?
